# Montelibero Stellar Anchor <https://montelibero.org>
# https://github.com/stellar/stellar-protocol/tree/master/ecosystem

ACCOUNTS=[
"GDI4PH6R2B4JDTMONRJA3BV4L3IBMXHWFCQPP5VTDSD3EE2ZFZGQJZZO"
]

[DOCUMENTATION]
ORG_NAME="MTL ASSETS"
ORG_DBA="MTL ASSETS"
ORG_URL="https://assets.montelibero.org"
ORG_LOGO="https://montelibero.org/images/logo.png"
ORG_DESCRIPTION=""
ORG_GITHUB="montelibero-org"
ORG_OFFICIAL_EMAIL="montelibero.fspe@gmail.com"
ORG_SUPPORT_EMAIL="montelibero.fspe@gmail.com"

[[CURRENCIES]]
code="EHIN"
issuer="GDI4PH6R2B4JDTMONRJA3BV4L3IBMXHWFCQPP5VTDSD3EE2ZFZGQJZZO"
status="live"
display_decimals=2
anchor_asset_type="other"
is_asset_anchored=false
name="EHIN"
desc="EHIN - a personal token fixes the issuer's obligations to provide their service provider within 1 hour of working time for 1 token in the field of his professional competencies and capabilities."
image="https://assets.montelibero.org/images/logo/EHIN-GDI4PH6R2B4JDTMONRJA3BV4L3IBMXHWFCQPP5VTDSD3EE2ZFZGQJZZO.png"

[[CURRENCIES]]
code="NIRO"
issuer="GCOP3XDXTEHWPRXT3NSPPPR3RCHLLK6CUZI3S6RUWGEAKDD73IEU5H3E"
status="live"
display_decimals=2
anchor_asset_type="other"
is_asset_anchored=false
name="Niro Korb"
desc="A personal token fixes Victor Korb's readiness to provide services to its bearer within the limits of his professional competencies and capabilities at the rate of 1 hour for 1 token, and if refused for any reason, the obligation to redeem the token at a fixed price of 4 EurMTL."
image="https://assets.montelibero.org/images/logo/NIRO-GCOP3XDXTEHWPRXT3NSPPPR3RCHLLK6CUZI3S6RUWGEAKDD73IEU5H3E.png"

[[CURRENCIES]]
code="GPA"
issuer="GBGGX7QD3JCPFKOJTLBRAFU3SIME3WSNDXETWI63EDCORLBB6HIP2CRR"
status="live"
display_decimals=2
anchor_asset_type="other"
is_asset_anchored=false
name="GPA"
desc="GPA is a token of the same name company, which guarantees its owner monthly payments in EURMTL in the amount of 2% of the invested amount (at least 100 tokens) due to trading operations."
image="https://assets.montelibero.org/images/logo/GPA-GBGGX7QD3JCPFKOJTLBRAFU3SIME3WSNDXETWI63EDCORLBB6HIP2CRR.png"

[[CURRENCIES]]
code="GPACAR"
issuer="GBGGX7QD3JCPFKOJTLBRAFU3SIME3WSNDXETWI63EDCORLBB6HIP2CRR"
status="live"
display_decimals=2
anchor_asset_type="other"
is_asset_anchored=false
name="GPACAR"
desc="GPACAR is a token that fixes the obligations of the issuer in the field of acquisition and commercial management of car rental, with which you can invest through EURMTL or your own cars in order to extract rental income from them with the right to exchange tokens back for cars at the request of the depositor."
image="https://assets.montelibero.org/images/logo/GPACAR-GBGGX7QD3JCPFKOJTLBRAFU3SIME3WSNDXETWI63EDCORLBB6HIP2CRR.png"
